In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style("whitegrid")
plt.rcParams["figure.figsize"] = (12, 5)

### Loading files

In [3]:
arc = pd.read_csv("../data/raw/data_arc.csv")
bulk_additions = pd.read_csv("../data/raw/data_bulk.csv")
bulk_additions_time = pd.read_csv("../data/raw/data_bulk_time.csv")
stirring_gas = pd.read_csv("../data/raw/data_gas.csv")
temperature = pd.read_csv("../data/raw/data_temp.csv")
temperature_full = pd.read_csv("../data/raw/data_temp_FULL_with_test.csv")
wire_additions = pd.read_csv("../data/raw/data_wire.csv")
wire_additions_time = pd.read_csv("../data/raw/data_wire_time.csv")

datasets = {
    "arc": arc,
    "bulk_additions": bulk_additions,
    "bulk_additions_time": bulk_additions_time,
    "stirring_gas": stirring_gas,
    "temperature": temperature,
    "temperature_full": temperature_full,
    "wire_additions": wire_additions,
    "wire_additions_time": wire_additions_time,
}

In [4]:
for name, df in datasets.items():
    print(f"\n{'='*60}")
    print(f"  {name}  —  {df.shape[0]} rows × {df.shape[1]} columns")
    print(f"{'='*60}")
    print(f"Columns: {list(df.columns)}")
    print(f"\nDtypes:\n{df.dtypes}")
    print(f"\nNull counts:\n{df.isnull().sum()[df.isnull().sum() > 0]}")
    if df.isnull().sum().sum() == 0:
        print("No nulls.")
    print(f"\nSample rows:")
    display(df.head(3))

============================================================
  arc  —  14876 rows × 5 columns
============================================================
Columns: ['key', 'Heating start', 'Heating end', 'Active power', 'Reactive power']

Dtypes:
key                 int64
Heating start         str
Heating end           str
Active power      float64
Reactive power    float64
dtype: object

Null counts:
Series([], dtype: int64)
No nulls.

Sample rows:

   key        Heating start          Heating end  Active power  Reactive power
0    1  2019-05-03 11:02:14  2019-05-03 11:06:02      0.976059        0.687084
1    1  2019-05-03 11:07:28  2019-05-03 11:10:33      0.805607        0.520285
2    1  2019-05-03 11:11:44  2019-05-03 11:14:36      0.744363        0.498805

============================================================
  bulk_additions  —  3129 rows × 16 columns
============================================================
Columns: ['key', 'Bulk 1', 'Bulk 2', 'Bulk 3', 'Bulk 4', 'Bulk 5', 'Bulk 6', 'Bulk 7', 'Bulk 8', 'Bulk 9', 'Bulk 10', 'Bulk 11', 'Bulk 12', 'Bulk 13', 'Bulk 14', 'Bulk 15']

Dtypes:
key          int64
Bulk 1     float64
Bulk 2     float64
Bulk 3     float64
Bulk 4     float64
Bulk 5     float64
Bulk 6     float64
Bulk 7     float64
Bulk 8     float64
Bulk 9     float64
Bulk 10    float64
Bulk 11    float64
Bulk 12    float64
Bulk 13    float64
Bulk 14    float64
Bulk 15    float64
dtype: object

Null counts:
Bulk 1     2877
Bulk 2     3107
Bulk 3     1831
Bulk 4     2115
Bulk 5     3052
Bulk 6     2553
Bulk 7     3104
Bulk 8     3128
Bulk 9     3110
Bulk 10    2953
Bulk 11    2952
Bulk 12     679
Bulk 13    3111
Bulk 14     323
Bulk 15     881
dtype: int64

Sample rows:

,key,Bulk 1,Bulk 2,Bulk 3,Bulk 4,Bulk 5,Bulk 6,Bulk 7,Bulk 8,Bulk 9,Bulk 10,Bulk 11,Bulk 12,Bulk 13,Bulk 14,Bulk 15
0,1,NaN,NaN,NaN,43.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,206.0,NaN,150.0,154.0
1,2,NaN,NaN,NaN,73.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,206.0,NaN,149.0,154.0
2,3,NaN,NaN,NaN,34.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,205.0,NaN,152.0,153.0

============================================================
  bulk_additions_time  —  3129 rows × 16 columns
============================================================
Columns: ['key', 'Bulk 1', 'Bulk 2', 'Bulk 3', 'Bulk 4', 'Bulk 5', 'Bulk 6', 'Bulk 7', 'Bulk 8', 'Bulk 9', 'Bulk 10', 'Bulk 11', 'Bulk 12', 'Bulk 13', 'Bulk 14', 'Bulk 15']

Dtypes:
key        int64
Bulk 1       str
Bulk 2       str
Bulk 3       str
Bulk 4       str
Bulk 5       str
Bulk 6       str
Bulk 7       str
Bulk 8       str
Bulk 9       str
Bulk 10      str
Bulk 11      str
Bulk 12      str
Bulk 13      str
Bulk 14      str
Bulk 15      str
dtype: object

Null counts:
Bulk 1     2877
Bulk 2     3107
Bulk 3     1831
Bulk 4     2115
Bulk 5     3052
Bulk 6     2553
Bulk 7     3104
Bulk 8     3128
Bulk 9     3110
Bulk 10    2953
Bulk 11    2952
Bulk 12     679
Bulk 13    3111
Bulk 14     323
Bulk 15     881
dtype: int64

Sample rows:

,key,Bulk 1,Bulk 2,Bulk 3,Bulk 4,Bulk 5,Bulk 6,Bulk 7,Bulk 8,Bulk 9,Bulk 10,Bulk 11,Bulk 12,Bulk 13,Bulk 14,Bulk 15
0,1,NaN,NaN,NaN,2019-05-03 11:21:30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-03 11:03:52,NaN,2019-05-03 11:03:52,2019-05-03 11:03:52
1,2,NaN,NaN,NaN,2019-05-03 11:46:38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-03 11:40:20,NaN,2019-05-03 11:40:20,2019-05-03 11:40:20
2,3,NaN,NaN,NaN,2019-05-03 12:31:06,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2019-05-03 12:09:40,NaN,2019-05-03 12:09:40,2019-05-03 12:09:40

============================================================
  stirring_gas  —  3239 rows × 2 columns
============================================================
Columns: ['key', 'Gas 1']

Dtypes:
key        int64
Gas 1    float64
dtype: object

Null counts:
Series([], dtype: int64)
No nulls.

Sample rows:

   key      Gas 1
0    1  29.749986
1    2  12.555561
2    3  28.554793

============================================================
  temperature  —  15907 rows × 3 columns
============================================================
Columns: ['key', 'time', 'Temperature']

Dtypes:
key              int64
time               str
Temperature    float64
dtype: object

Null counts:
Temperature    2901
dtype: int64

Sample rows:

   key                 time  Temperature
0    1  2019-05-03 11:16:18       1571.0
1    1  2019-05-03 11:25:53       1604.0
2    1  2019-05-03 11:29:11       1618.0

============================================================
  temperature_full  —  15907 rows × 3 columns
============================================================
Columns: ['key', 'time', 'Temperature']

Dtypes:
key              int64
time               str
Temperature    float64
dtype: object

Null counts:
Series([], dtype: int64)
No nulls.

Sample rows:

   key                 time  Temperature
0    1  2019-05-03 11:16:18       1571.0
1    1  2019-05-03 11:25:53       1604.0
2    1  2019-05-03 11:29:11       1618.0

============================================================
  wire_additions  —  3081 rows × 10 columns
============================================================
Columns: ['key', 'Wire 1', 'Wire 2', 'Wire 3', 'Wire 4', 'Wire 5', 'Wire 6', 'Wire 7', 'Wire 8', 'Wire 9']

Dtypes:
key         int64
Wire 1    float64
Wire 2    float64
Wire 3    float64
Wire 4    float64
Wire 5    float64
Wire 6    float64
Wire 7    float64
Wire 8    float64
Wire 9    float64
dtype: object

Null counts:
Wire 1      26
Wire 2    2002
Wire 3    3018
Wire 4    3067
Wire 5    3080
Wire 6    3008
Wire 7    3070
Wire 8    3062
Wire 9    3052
dtype: int64

Sample rows:

,key,Wire 1,Wire 2,Wire 3,Wire 4,Wire 5,Wire 6,Wire 7,Wire 8,Wire 9
0,1,60.059998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,96.052315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,91.160157,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

============================================================
  wire_additions_time  —  3081 rows × 10 columns
============================================================
Columns: ['key', 'Wire 1', 'Wire 2', 'Wire 3', 'Wire 4', 'Wire 5', 'Wire 6', 'Wire 7', 'Wire 8', 'Wire 9']

Dtypes:
key       int64
Wire 1      str
Wire 2      str
Wire 3      str
Wire 4      str
Wire 5      str
Wire 6      str
Wire 7      str
Wire 8      str
Wire 9      str
dtype: object

Null counts:
Wire 1      26
Wire 2    2002
Wire 3    3018
Wire 4    3067
Wire 5    3080
Wire 6    3008
Wire 7    3070
Wire 8    3062
Wire 9    3052
dtype: int64

Sample rows:

,key,Wire 1,Wire 2,Wire 3,Wire 4,Wire 5,Wire 6,Wire 7,Wire 8,Wire 9
0,1,2019-05-03 11:11:41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,2019-05-03 11:46:10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,2019-05-03 12:13:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN